serviceName: apollo-gem-service
development: true
DATABASE:
  READDB:
    CONNECTION_STRING: postgres://postgres:2705@0.0.0.0/tsdb?sslmode=disable
    dbType: postgres
    migrationFilePath: migrations
  WRITEDB:
    CONNECTION_STRING: postgres://postgres:2705@0.0.0.0/tsdb?sslmode=disable
    dbType: postgres
    migrationFilePath: migrations
http:
  port: :5001
  development: true
  shutdownTimeout: 15
  resources: ["internal/resources/en.json", "internal/resources/vi.json"]
  rateLimiting:
    rateFormat: "10000-S"
grpc:
  port: :5005
  development: true
  maxConnectionIdle: 5
  timeout: 15
  maxConnectionAge: 5
  time: 10
LOGGER:
  LOGGER_LEVEL: debug
  devMode: false
  encoder: json
jaeger:
  enable: true
  serviceName: apollo-gem-service
  hostPort: AWS_DATA
  logSpans: false
KAFKA:
  CONFIG:
    BROKERS: "b-1.dev.3de1i9.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.dev.3de1i9.c5.kafka.ap-southeast-1.amazonaws.com:9096"
    USERNAME: admin
    PASSWORD: H4ppyN3wYeAr2023!!
  consumers:
    gemCreateConsumer:
      groupId: kaypay.local.gem.source.create.consumer
      topicName: kaypay.dev.gem.source.create.byte
      numWorker: 1
  producers:
    gemCreateProducer:
      topicName: kaypay.local.gem.source.notification.create.byte
      initTopic: true
      numPartitions: 10
      replicationFactor: 1
REDIS:
  ADDRESS: AWS_DATA
  PASSWORD: AWS_DATA
  db: 0
  poolSize: 300
healthcheck:
  interval: 10
  port: :6001
  goroutineThreshold: 100
metrics:
  prometheusPath: /metrics
  prometheusPort: :8001
SCHEDULER:
  CRON_EXPRESSION: "*/30 * * * *"
